language: ruby

services:
  - cassandra

install:
  - gem install cassandra

script:
  - cassandra-cli
  - DROP KEYSPACE demo;
  - exit;
  - cassandra-cli -host localhost -port 9160 -f schema.txt
  - ruby sample.rb




